"""Session handoff (WRIT-ROADMAP 18c): assemble what a successor needs to resume.

DERIVED, NEVER SUMMARIZED. Every section is a projection of state Writ already
holds (the session cache and the approved plan), so nothing here can drift from
its source and nothing requires a model call. A generated prose summary of a
session is exactly the artifact whose accuracy nobody can check afterwards, which
is what the post-compaction directive in this repo already warns about.

Files written come from `cache["files_written"]`, which is session-scoped by
construction, so another session's writes cannot appear here at all.
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

HANDOFF_DIR = ".claude/handoffs"

# Deliberately NOT `slice-*.json`: hooks/scripts/validate-handoff.sh is registered
# for that glob and validates a different artifact (a slice handoff, six required
# keys). That validator has zero rows in the audit stream and no producer; naming
# this file so it cannot match keeps a dead guard visibly dead instead of feeding
# it input it was never written for.
_NAME = "session-{sid}.md"

_UNCHECKED = re.compile(r"^- \[ \] (.+)$", re.M)
_FILE_ENTRY = re.compile(r"^- `([^`]+)`", re.M)


def handoff_path(session_id: str, project_root: str) -> Path:
    return Path(project_root) / HANDOFF_DIR / _NAME.format(sid=session_id)


def _section(title: str, items: list[str], empty: str) -> list[str]:
    out = [f"## {title}", ""]
    out.extend(f"- {i}" for i in items) if items else out.append(empty)
    out.append("")
    return out


def render_handoff(session_id: str, cache: dict, plan_text: str) -> str:
    """Build the handoff document. Pure: no I/O, no graph, no daemon."""
    mode = cache.get("mode") or "unset"
    phase = cache.get("current_phase") or "none"
    gates = cache.get("gates_approved") or []
    rule_ids = cache.get("loaded_rule_ids") or []
    written = cache.get("files_written") or []

    # Only the `## Files` block, so Analysis prose cannot reach the file list.
    files_block = ""
    if plan_text:
        parts = plan_text.split("## Files", 1)
        if len(parts) == 2:
            files_block = parts[1].split("\n## ", 1)[0]
    plan_files = _FILE_ENTRY.findall(files_block)
    open_items = _UNCHECKED.findall(plan_text or "")

    lines = [
        f"# Session handoff: {session_id}",
        "",
        "Generated by `writ handoff`. Every line below is derived from the session",
        "cache and the approved plan; nothing is summarized.",
        "",
        "## Where the session stands",
        "",
        f"- mode: {mode}",
        f"- phase: {phase}",
        f"- gates approved: {', '.join(gates) if gates else 'none'}",
        "",
    ]
    lines += _section("Files the plan declared", plan_files, "No approved plan.")
    lines += _section("Files this session wrote", written, "Nothing written yet.")
    lines += _section("Open items (unchecked capabilities)", open_items, "None open.")
    # Count first, then a wrapped block rather than one bullet per id. Rendering a
    # real session showed the one-per-line form at 220 of the document's 260 lines,
    # burying every section a successor actually needs. The ids stay (they are the
    # session's rule provenance) but they stop being the document.
    lines += ["## Rules loaded this session", ""]
    if rule_ids:
        lines.append(f"{len(rule_ids)} rules. Full list also in the session cache.")
        lines.append("")
        lines.extend(textwrap.wrap(
            ", ".join(rule_ids), width=88,
            # A rule id split across a line break is not copy-pasteable and reads as
            # corruption. Ids are hyphenated, so both defaults have to be turned off.
            break_on_hyphens=False, break_long_words=False,
        ))
    else:
        lines.append("No rules loaded.")
    lines.append("")
    return "\n".join(lines) + "\n"


def build_handoff(session_id: str, project_root: str) -> str:
    """Gather this session's state from disk and render it."""
    from writ.session.cache import _read_cache

    try:
        cache = _read_cache(session_id) or {}
    except Exception:
        cache = {}
    plan = Path(project_root) / ".claude" / "plans" / session_id / "plan.md"
    try:
        plan_text = plan.read_text()
    except OSError:
        plan_text = ""
    return render_handoff(session_id, cache, plan_text)


def write_handoff(session_id: str, project_root: str) -> Path:
    """Render and write the handoff. Returns the path written."""
    p = handoff_path(session_id, project_root)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(build_handoff(session_id, project_root))
    return p
